### ISSUE TITLE
OPEN POLL

### ISSUE THREAD

**Issue by Lolimipsu** [lain-making-bread/LowRes-Bot#1]
just kidding, any issues or implementations that I can help with?

**Comment by lain-making-bread** [comment]
* play music feature 
* editing the meme function so that it accepts images as input and update the default templates for it
* host the bot in the cloud 
* update the AI function so we can access the history when generating a new reply
* updating the README file

**Comment by lain-making-bread** [comment]
closing this issue and moving this chat to #3
